version: '3.8'

services:
  app:
    build: .
    container_name: vibing_oreo_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "8001:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DB_CONNECTION=sqlite
      # For SQLite, optionally set DB_DATABASE path; Laravel defaults to database/database.sqlite
      # - DB_DATABASE=/var/www/html/database/database.sqlite
    tty: true
    command: >-
      bash -lc "/usr/local/bin/entrypoint.sh"

