version: '3.8'
services:
  app:
    image: 'php:8.1-fpm'
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - '8000:8000'
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
